name: Test Build User API (Releases)
on:
  push:
    branches:
      - 'main'
      
  # Allow run workflow manually from Action tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: Setup .NET 6.0.x 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
              6.0.x
      - name: Restore dependency
        run: dotnet restore
      - name: Buid User API
        run: dotnet build -c Release --no-restore





